import index from './corpus-index.json'

/**
 * What the graph knows, carried into the running app.
 *
 * The read model is built from the `historial` branch and has no way to know
 * what did not make it in. Measured black-box, 54% of the version records the
 * graph holds are never served, and 77% of multi-version normas are missing at
 * least one — and every one of those answers looks exactly like a complete one.
 * That is the worst failure mode this corpus has: not a wrong answer that can
 * be spotted, but a confident partial answer that cannot.
 *
 * `corpus-index.json` is generated by scripts/build-corpus-index.ts and
 * committed, because the Docker build context is `site/` and `graph_shards/`
 * lives at the repo root. It holds only what is worth carrying: normas with
 * more than one version (the only ones whose history can be short) and the 160
 * LeyChile marks as having deferred entry into force.
 *
 * Nothing here asserts the graph is right. It is a scrape too. But a version
 * the graph HAS and the API lacks is a hole in the read model, and saying so is
 * strictly better than the silence that preceded it.
 */

interface CorpusIndex {
  generated: string
  nodes: number
  /** idNorma → number of distinct real `desde` dates, for multi-version normas. */
  versions: Record<string, number>
  /** idNorma → deferred-entry markers: `fecha:YYYY-MM-DD` or `evento`. */
  deferred: Record<string, string[]>
}

const CORPUS = index as CorpusIndex

/** The date this snapshot of the graph was taken. */
export const INDEX_GENERATED = CORPUS.generated

/** How many versions the graph records, or null when it says nothing. */
export function expectedVersions(idNorma: number): number | null {
  return CORPUS.versions[String(idNorma)] ?? null
}

export interface DeferredMark {
  kind: 'fecha' | 'evento'
  /** Present for `fecha`: the date LeyChile assigns to the deferred version. */
  desde?: string
}

/** LeyChile's own deferred-entry markers for this norma, if any. */
export function deferredVigencia(idNorma: number): DeferredMark[] {
  const raw = CORPUS.deferred[String(idNorma)]
  if (!raw) return []
  return raw.map((m) =>
    m.startsWith('fecha:')
      ? { kind: 'fecha' as const, desde: m.slice('fecha:'.length) }
      : { kind: 'evento' as const },
  )
}

/**
 * The warning for a history the read model cannot fully serve.
 *
 * Returned only when the shortfall is real: the graph knows more versions than
 * were served. Equal or greater counts say nothing — a served history longer
 * than the graph's is not a defect, it means the pipeline is ahead of this
 * snapshot, which is the normal direction of travel.
 */
export function incompleteHistoryWarning(idNorma: number, served: number): string | null {
  const expected = expectedVersions(idNorma)
  if (expected === null || served >= expected) return null
  const missing = expected - served
  return (
    `⚠ HISTORIAL INCOMPLETO: se sirven ${served} versiones, pero el catálogo registra ` +
    `${expected} para esta norma — faltan ${missing}. Una consulta con \`fecha\` dentro de ` +
    'un tramo faltante devolverá el texto de una versión anterior sin avisar. ' +
    `Trata las fechas límite con cuidado y contrasta con LeyChile. (Catálogo al ${CORPUS.generated}.)`
  )
}

/** The warning for a norma whose entry into force LeyChile marks as deferred. */
export function deferredVigenciaWarning(idNorma: number): string | null {
  const marks = deferredVigencia(idNorma)
  if (marks.length === 0) return null
  const fechas = marks.filter((m) => m.kind === 'fecha' && m.desde).map((m) => m.desde!)
  const evento = marks.some((m) => m.kind === 'evento')
  const parts = [
    '⚠ VIGENCIA DIFERIDA: LeyChile marca al menos una versión de esta norma con entrada ' +
    'en vigencia (o derogación) diferida.',
  ]
  if (fechas.length) parts.push(`Diferida a fecha: ${[...new Set(fechas)].sort().join(', ')}.`)
  if (evento) {
    parts.push(
      'Una parte está condicionada a un hecho (un reglamento, una puesta en marcha) y no ' +
      'a una fecha, así que no se puede fechar: verifica si el hecho ya ocurrió.',
    )
  }
  parts.push('El texto que se muestra puede no ser el que regía en la fecha consultada.')
  return parts.join(' ')
}
