/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeyNumeroIndexRouteImport } from './routes/ley.$numero.index'
import { Route as LeyNumeroFechaRouteImport } from './routes/ley.$numero.$fecha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeyNumeroIndexRoute = LeyNumeroIndexRouteImport.update({
  id: '/ley/$numero/',
  path: '/ley/$numero/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeyNumeroFechaRoute = LeyNumeroFechaRouteImport.update({
  id: '/ley/$numero/$fecha',
  path: '/ley/$numero/$fecha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ley/$numero/$fecha': typeof LeyNumeroFechaRoute
  '/ley/$numero/': typeof LeyNumeroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ley/$numero/$fecha': typeof LeyNumeroFechaRoute
  '/ley/$numero': typeof LeyNumeroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ley/$numero/$fecha': typeof LeyNumeroFechaRoute
  '/ley/$numero/': typeof LeyNumeroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ley/$numero/$fecha' | '/ley/$numero/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ley/$numero/$fecha' | '/ley/$numero'
  id: '__root__' | '/' | '/ley/$numero/$fecha' | '/ley/$numero/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeyNumeroFechaRoute: typeof LeyNumeroFechaRoute
  LeyNumeroIndexRoute: typeof LeyNumeroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ley/$numero/': {
      id: '/ley/$numero/'
      path: '/ley/$numero'
      fullPath: '/ley/$numero/'
      preLoaderRoute: typeof LeyNumeroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ley/$numero/$fecha': {
      id: '/ley/$numero/$fecha'
      path: '/ley/$numero/$fecha'
      fullPath: '/ley/$numero/$fecha'
      preLoaderRoute: typeof LeyNumeroFechaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeyNumeroFechaRoute: LeyNumeroFechaRoute,
  LeyNumeroIndexRoute: LeyNumeroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
